import { addDays, format, startOfDay } from 'date-fns'
import type { DataStore } from '../types.js'

export function createSeedStore(): DataStore {
  const today = format(startOfDay(new Date()), 'yyyy-MM-dd')
  const validTo = format(addDays(new Date(), 90), 'yyyy-MM-dd')

  return {
    version: 1,
    users: [
      {
        id: 'u-admin',
        login: 'admin',
        fullName: 'Тимофей',
        phone: '+375 29 713 10 01',
        role: 'ADMIN',
        isActive: true,
        color: '#16a34a',
        pilotSimulators: [],
      },
      {
        id: 'u-manager',
        login: 'manager',
        fullName: 'Иван Менеджеров',
        phone: '+375 (12) 1234567',
        role: 'MANAGER',
        isActive: true,
        color: '#2563eb',
        pilotSimulators: [],
      },
      {
        id: 'u-pilot-b737',
        login: 'pilot_b737',
        fullName: 'Николай',
        phone: '+375 (12) 1111111',
        role: 'PILOT',
        isActive: true,
        color: '#0891b2',
        pilotSimulators: ['boeing-737'],
      },
      {
        id: 'u-pilot-mi2',
        login: 'pilot_mi2',
        fullName: 'Валентин',
        phone: '+375 (12) 2222222',
        role: 'PILOT',
        isActive: true,
        color: '#ea580c',
        pilotSimulators: ['mi-2'],
      },
    ],
    bookings: [
      {
        id: 'b-1',
        date: today,
        startTime: '12:00',
        endTime: '12:30',
        durationMin: 30,
        simulatorSlug: 'boeing-737',
        name: 'Арсений',
        phone: '+375 (12) 1234567',
        email: 'client@example.com',
        status: 'CONFIRMED',
        paid: false,
        paymentMethod: 'OFFLINE',
        comment: 'Будем с ребенком',
        isBirthdayPromo: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    calendar: {},
    staffShifts: [],
    certificates: [
      {
        id: 'c-1',
        number: '№111111',
        phone: '+375 (12) 1234567',
        fullName: 'Никита Швепс',
        durationMin: 30,
        paymentStatus: 'PAID',
        validFrom: today,
        validTo,
        simulatorSlug: 'boeing-737',
        status: 'ACTIVE',
        comment: 'Придут с ребенком',
        createdAt: new Date().toISOString(),
      },
    ],
    waitingRoom: [],
    flightPrices: [
      { id: 'fp-1', durationMin: 30, simulatorSlug: 'mi-2', priceByn: 170 },
      { id: 'fp-2', durationMin: 30, simulatorSlug: 'boeing-737', priceByn: 170 },
      { id: 'fp-3', durationMin: 60, simulatorSlug: 'mi-2', priceByn: 300 },
      { id: 'fp-4', durationMin: 60, simulatorSlug: 'boeing-737', priceByn: 300 },
      { id: 'fp-5', durationMin: 90, simulatorSlug: 'boeing-737', priceByn: 400 },
      { id: 'fp-6', durationMin: 120, simulatorSlug: 'boeing-737', priceByn: 450 },
    ],
    certPrices: [
      { id: 'cp-1', durationMin: 30, simulatorSlug: 'mi-2', priceByn: 170 },
      { id: 'cp-2', durationMin: 30, simulatorSlug: 'boeing-737', priceByn: 170 },
      { id: 'cp-3', durationMin: 60, simulatorSlug: 'mi-2', priceByn: 300 },
      { id: 'cp-4', durationMin: 60, simulatorSlug: 'boeing-737', priceByn: 300 },
      { id: 'cp-5', durationMin: 60, simulatorSlug: 'combo', priceByn: 300 },
    ],
    promos: [
      {
        id: 'pr-1',
        name: 'День рождения',
        discountPercent: 15,
        startDate: '2025-01-01',
        endDate: '2027-12-31',
        productType: 'Boeing',
        promoType: 'BIRTHDAY',
        active: true,
      },
      {
        id: 'pr-2',
        name: 'Счастливые часы',
        discountPercent: 10,
        startDate: '2025-01-01',
        endDate: '2027-12-31',
        productType: 'Ми-2',
        promoType: 'HAPPY_HOURS',
        active: true,
      },
    ],
    documents: [
      { key: 'privacy', title: 'Политика конфиденциальности', content: '' },
      { key: 'offer', title: 'Договор оферты', content: '' },
    ],
    contacts: {
      phone: '+375 (12) 1234567',
      email: 'info@aviator.by',
      hours: '12:00 - 21:00 по мск',
    },
    gallery: {
      'boeing-737': [],
      'mi-2': [],
      'summer-school': [],
    },
    workHours: [],
    maintenance: [],
    optionLists: {
      duration: [
        { id: 'd-30', value: '30', label: '30 минут', sortOrder: 1 },
        { id: 'd-60', value: '60', label: '60 минут', sortOrder: 2 },
        { id: 'd-90', value: '90', label: '90 минут', sortOrder: 3 },
        { id: 'd-120', value: '120', label: '120 минут', sortOrder: 4 },
      ],
      simulator: [
        { id: 's-b737', value: 'boeing-737', label: 'Boeing 737', sortOrder: 1 },
        { id: 's-mi2', value: 'mi-2', label: 'Ми-2', sortOrder: 2 },
      ],
    },
    settings: { bookingWindowMonths: 3 },
    counters: { certificate: 111112 },
    pendingCodes: [],
  }
}
